SLING-11716 add caching in caconfig
apache/sling-org-apache-sling-caconfig-impl pull request #6
Opened 2022-12-05 10:41 UTC by joerghoh

* cache successful resolutions and avoid duplicate resolutions of the same resource (path) and cah 
* updates to a later version of the ResourceResolver API

2022-12-21 09:56 UTC, stefanseifert requested changes
i've one major concern with this PR: it caches the ConfigurationBuilderImpl instance - but the hard work that is done is when actually calling the various methods of ConfigurationBuilder, and the return values of that are not cached. did you confirm that this change has any positive effect on performance? i think we need to implement the caching on the output results of ConfigurationBuilder, maybe implementation a ConfigurationBuilder facade that adds caching.

additional note: this code also assumes a resource resolver is never used in a long-running scenario with using refresh in between. although an anti-pattern, it is possible that this pattern is used e.g. in OSGi services. at least we have to clearly document it in both javadoc and site if we change this behavior. if we think we have to "officially" support the long-running use case scenario, we have to update the caconfig API as well to (optionally, non-default) provide a way to resolve a caconfig with bypassing the cache.

2022-12-21 09:56 UTC, stefanseifert commented on src/main/java/org/apache/sling/caconfig/impl/ConfigurationResolverImpl.java
> +            return buildFor(resource);
i do not understand this line - it is dead code assuming resource is never null according to @NotNull annotation

2022-12-21 09:56 UTC, stefanseifert commented on src/main/java/org/apache/sling/caconfig/impl/ConfigurationResolverImpl.java
> +            LOG.trace("created configurationBuilde for {}",resource.getPath());
typo -> configurationBuilder

2022-12-21 09:56 UTC, stefanseifert commented on src/main/java/org/apache/sling/caconfig/impl/ConfigurationResolverImpl.java
> +        if (!configurationBuilderCache.containsKey(resource.getPath())) {
consider using Map.computeIfAbsent (here and also above for the property map)

2024-01-21 16:52 UTC, joerghoh commented
closed in favor of #9.

2024-01-21 16:52 UTC, closed without merging